// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EgyDynamic_Task.Models;

public partial class EgyDynamic_TaskContext : DbContext
{
    public EgyDynamic_TaskContext()
    {
    }

    public EgyDynamic_TaskContext(DbContextOptions<EgyDynamic_TaskContext> options)
        : base(options)
    {
    }

    public virtual DbSet<العميل> العميلs { get; set; }

    public virtual DbSet<الموظف> الموظفs { get; set; }

    public virtual DbSet<مكالمه_العميل> مكالمه_العميلs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<العميل>(entity =>
        {
            entity.HasKey(e => e.كود_العميل).HasName("PK__العميل__36B81C84A95AD8F1");

            entity.HasOne(d => d.اخر_تعديلNavigation).WithMany(p => p.العميلاخر_تعديلNavigations).HasConstraintName("FK__العميل__اخر تعدي__534D60F1");

            entity.HasOne(d => d.ادخال_بواسطةNavigation).WithMany(p => p.العميلادخال_بواسطةNavigations).HasConstraintName("FK__العميل__ادخال بو__52593CB8");
        });

        modelBuilder.Entity<الموظف>(entity =>
        {
            entity.HasKey(e => e.كود_الموظف).HasName("PK__الموظف__BEEAEAD9258A05FA");
        });

        modelBuilder.Entity<مكالمه_العميل>(entity =>
        {
            entity.HasKey(e => e.كود_مكالمه_العميل).HasName("PK__مكالمه_ا__AB9526E2BA101A4E");

            entity.HasOne(d => d.اخر_تعديلNavigation).WithMany(p => p.مكالمه_العميلاخر_تعديلNavigations).HasConstraintName("FK__مكالمه_ال__اخر ت__59063A47");

            entity.HasOne(d => d.ادخال_بواسطهNavigation).WithMany(p => p.مكالمه_العميلادخال_بواسطهNavigations).HasConstraintName("FK__مكالمه_ال__ادخال__571DF1D5");

            entity.HasOne(d => d.العميلNavigation).WithMany(p => p.مكالمه_العميلs).HasConstraintName("FK__مكالمه_ال__العمي__5812160E");

            entity.HasOne(d => d.الموظفNavigation).WithMany(p => p.مكالمه_العميلالموظفNavigations).HasConstraintName("FK__مكالمه_ال__الموظ__5629CD9C");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}