// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EgyDynamic_Task.Models;

[Table("الموظف")]
public partial class الموظف
{
    [Key]
    [Column("كود الموظف")]
    public int كود_الموظف { get; set; }

    [Required]
    [Column("اسم الموظف")]
    [StringLength(255)]
    public string اسم_الموظف { get; set; }

    [Required]
    [Column("اسم المستخدم")]
    [StringLength(255)]
    public string اسم_المستخدم { get; set; }

    [Required]
    [Column("كلمه المرور")]
    [StringLength(255)]
    public string كلمه_المرور { get; set; }

    [InverseProperty("اخر_تعديلNavigation")]
    public virtual ICollection<العميل> العميلاخر_تعديلNavigations { get; set; } = new List<العميل>();

    [InverseProperty("ادخال_بواسطةNavigation")]
    public virtual ICollection<العميل> العميلادخال_بواسطةNavigations { get; set; } = new List<العميل>();

    [InverseProperty("اخر_تعديلNavigation")]
    public virtual ICollection<مكالمه_العميل> مكالمه_العميلاخر_تعديلNavigations { get; set; } = new List<مكالمه_العميل>();

    [InverseProperty("ادخال_بواسطهNavigation")]
    public virtual ICollection<مكالمه_العميل> مكالمه_العميلادخال_بواسطهNavigations { get; set; } = new List<مكالمه_العميل>();

    [InverseProperty("الموظفNavigation")]
    public virtual ICollection<مكالمه_العميل> مكالمه_العميلالموظفNavigations { get; set; } = new List<مكالمه_العميل>();
}