// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EgyDynamic_Task.Models;

[Table("العميل")]
public partial class العميل
{
    [Key]
    public int كود_العميل { get; set; }

    [Column("اسم العميل")]
    [StringLength(255)]
    public string اسم_العميل { get; set; }

    [Column("عنوان العميل")]
    [StringLength(255)]
    public string عنوان_العميل { get; set; }

    [StringLength(255)]
    public string الموبايل { get; set; }

    [Column("تليفون 1")]
    [StringLength(255)]
    public string تليفون_1 { get; set; }

    [Column("تليفون 2")]
    [StringLength(255)]
    public string تليفون_2 { get; set; }

    [StringLength(255)]
    public string واتس { get; set; }

    [StringLength(255)]
    public string ايميل { get; set; }

    [StringLength(255)]
    public string الجنسيه { get; set; }

    [Column("محل الاقامه")]
    [StringLength(255)]
    public string محل_الاقامه { get; set; }

    [StringLength(255)]
    public string توصيف { get; set; }

    [StringLength(255)]
    public string الوظيفة { get; set; }

    [Column("ادخال بواسطة")]
    public int? ادخال_بواسطة { get; set; }

    [Column("تاريخ الادخال")]
    public DateTime? تاريخ_الادخال { get; set; }

    [Column("اخر تعديل")]
    public int? اخر_تعديل { get; set; }

    [Column("اخر تعديل في")]
    public DateTime? اخر_تعديل_في { get; set; }

    [Column("رجل المبيعات")]
    [StringLength(255)]
    public string رجل_المبيعات { get; set; }

    [Column("مصدر العميل")]
    [StringLength(255)]
    public string مصدر_العميل { get; set; }

    [Column("تصنيف العميل")]
    [StringLength(255)]
    public string تصنيف_العميل { get; set; }

    [ForeignKey("اخر_تعديل")]
    [InverseProperty("العميلاخر_تعديلNavigations")]
    public virtual الموظف اخر_تعديلNavigation { get; set; }

    [ForeignKey("ادخال_بواسطة")]
    [InverseProperty("العميلادخال_بواسطةNavigations")]
    public virtual الموظف ادخال_بواسطةNavigation { get; set; }

    [InverseProperty("العميلNavigation")]
    public virtual ICollection<مكالمه_العميل> مكالمه_العميلs { get; set; } = new List<مكالمه_العميل>();
}