// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EgyDynamic_Task.Models;

[Table("مكالمه_العميل")]
public partial class مكالمه_العميل
{
    [Key]
    public int كود_مكالمه_العميل { get; set; }

    [StringLength(255)]
    public string التوصيف { get; set; }

    [Column("عنوان المكالمة")]
    public int? عنوان_المكالمة { get; set; }

    public DateTime? التاريخ { get; set; }

    [StringLength(255)]
    public string المشروع { get; set; }

    public int? الموظف { get; set; }

    [Column("هل تمت")]
    public bool? هل_تمت { get; set; }

    [Column("نوع المكالمه")]
    [StringLength(255)]
    public string نوع_المكالمه { get; set; }

    [Column("هل وارد")]
    public bool? هل_وارد { get; set; }

    [Column("ادخال بواسطه")]
    public int? ادخال_بواسطه { get; set; }

    [Column("تاريخ الادخال")]
    public DateTime? تاريخ_الادخال { get; set; }

    [Column("اخر تعديل في")]
    public DateTime? اخر_تعديل_في { get; set; }

    public int? العميل { get; set; }

    [Column("اخر تعديل")]
    public int? اخر_تعديل { get; set; }

    [ForeignKey("اخر_تعديل")]
    [InverseProperty("مكالمه_العميلاخر_تعديلNavigations")]
    public virtual الموظف اخر_تعديلNavigation { get; set; }

    [ForeignKey("ادخال_بواسطه")]
    [InverseProperty("مكالمه_العميلادخال_بواسطهNavigations")]
    public virtual الموظف ادخال_بواسطهNavigation { get; set; }

    [ForeignKey("العميل")]
    [InverseProperty("مكالمه_العميلs")]
    public virtual العميل العميلNavigation { get; set; }

    [ForeignKey("الموظف")]
    [InverseProperty("مكالمه_العميلالموظفNavigations")]
    public virtual الموظف الموظفNavigation { get; set; }
}